from flask import Flask, render_template, redirect, url_for, request, send_file
import pickle
import pandas as pd
import sqlite3

from datetime import datetime
from io import BytesIO
from urllib.parse import quote
import html
from pathlib import Path

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)


# ============================================================
# FLASK APPLICATION
# ============================================================

app = Flask(__name__)

# ============================================================
# MODULE 10 — MULTILINGUAL REPORT SUPPORT
# ============================================================

TAMIL_FONT_PATH = "/usr/share/fonts/opentype/noto/NotoSansTamil-Regular.ttf"

# Windows/local fallback paths are checked when available.
_TAMIL_FONT_CANDIDATES = [
    TAMIL_FONT_PATH,
    r"C:\Windows\Fonts\NotoSansTamil-Regular.ttf",
    r"C:\Windows\Fonts\NotoSansTamil.ttf",
]

for _font_path in _TAMIL_FONT_CANDIDATES:
    try:
        if Path(_font_path).exists():
            pdfmetrics.registerFont(TTFont("NotoTamil", _font_path))
            break
    except Exception:
        pass

TAMIL_FONT_AVAILABLE = "NotoTamil" in pdfmetrics.getRegisteredFontNames()

REPORT_LABELS = {
    "en": {
        "title": "CKDPredict",
        "subtitle": "Clinical Decision-Support Assessment Report",
        "summary": "1. Assessment Summary",
        "assessment_id": "Assessment ID",
        "date": "Assessment Date",
        "patient": "Patient Name",
        "age": "Age",
        "gender": "Gender",
        "prediction": "Prediction",
        "risk": "Risk Level",
        "confidence": "Model Confidence",
        "probability": "CKD Probability",
        "kidney": "2. Kidney Function — eGFR & GFR Category",
        "creatinine": "Serum Creatinine",
        "egfr": "eGFR",
        "category": "GFR Category",
        "description": "Category Description",
        "clinical": "3. Key Clinical Parameters",
        "history": "4. Medical History Factors",
        "xai": "5. Explainable AI — Prediction Factors",
        "support": "6. Clinical Decision Support",
        "warnings": "Early Warning Indicators",
        "recommendations": "Recommendations",
        "notice": "Decision Support Notice",
        "not_diagnosis": "This report is generated by CKDPredict for decision-support and educational purposes. It is not a medical diagnosis and should not replace professional medical evaluation, treatment, or emergency care.",
        "egfr_note": "eGFR is an estimated measure of kidney filtration. A GFR category alone does not confirm chronic kidney disease; clinical assessment and persistent findings over time are required.",
    },
    "ta": {
        "title": "CKDPredict",
        "subtitle": "மருத்துவ முடிவு ஆதரவு மதிப்பீட்டு அறிக்கை",
        "summary": "1. மதிப்பீட்டு சுருக்கம்",
        "assessment_id": "மதிப்பீட்டு எண்",
        "date": "மதிப்பீட்டு தேதி",
        "patient": "நோயாளியின் பெயர்",
        "age": "வயது",
        "gender": "பாலினம்",
        "prediction": "கணிப்பு முடிவு",
        "risk": "ஆபத்து நிலை",
        "confidence": "மாதிரி நம்பிக்கை",
        "probability": "CKD நிகழ்தகவு",
        "kidney": "2. சிறுநீரக செயல்பாடு — eGFR & GFR வகை",
        "creatinine": "Serum Creatinine",
        "egfr": "eGFR",
        "category": "GFR வகை",
        "description": "வகை விளக்கம்",
        "clinical": "3. முக்கிய மருத்துவ அளவுகள்",
        "history": "4. மருத்துவ வரலாறு காரணிகள்",
        "xai": "5. Explainable AI — கணிப்பு காரணிகள்",
        "support": "6. மருத்துவ முடிவு ஆதரவு",
        "warnings": "முக்கிய எச்சரிக்கைகள்",
        "recommendations": "பரிந்துரைகள்",
        "notice": "முடிவு ஆதரவு குறிப்பு",
        "not_diagnosis": "இந்த அறிக்கை CKDPredict மூலம் முடிவு ஆதரவு மற்றும் கல்வி நோக்கத்திற்காக உருவாக்கப்படுகிறது. இது மருத்துவ நோயறிதல் அல்ல; மருத்துவ நிபுணரின் மதிப்பீடு, சிகிச்சை அல்லது அவசர சிகிச்சைக்கு மாற்றாக பயன்படுத்தக்கூடாது.",
        "egfr_note": "eGFR என்பது சிறுநீரக வடிகட்டும் திறனை மதிப்பிடும் ஒரு கணிக்கப்பட்ட அளவாகும். GFR வகை மட்டும் நீண்டகால சிறுநீரக நோயை உறுதி செய்யாது; மருத்துவ மதிப்பீடும் காலப்போக்கில் தொடர்ச்சியான பரிசோதனையும் தேவை.",
    }
}

TAMIL_RESULT = {
    "Chronic Kidney Disease Detected": "நீண்டகால சிறுநீரக நோய் (CKD) கண்டறியப்பட்டது",
    "No Chronic Kidney Disease Detected": "நீண்டகால சிறுநீரக நோய் (CKD) கண்டறியப்படவில்லை",
    "High": "அதிக",
    "Low": "குறைவு",
    "Moderate": "மிதமான",
    "Important": "முக்கியம்",
    "Monitor": "கண்காணிக்கவும்",
}

def report_lang(value):
    return "ta" if str(value or "").lower().startswith("ta") else "en"

def rtext(value, lang="en"):
    if value is None or str(value).strip() == "":
        return "N/A"
    if lang == "ta":
        return TAMIL_RESULT.get(str(value), str(value))
    return str(value)




# ============================================================
# DATABASE
# ============================================================

DATABASE = "patient_history.db"


# ============================================================
# MODEL FEATURES
# ============================================================

MODEL_FEATURES = [
    "sg",
    "al",
    "hemo",
    "rc",
    "htn",
    "dm",
    "appet",
    "pc"
]


# ============================================================
# FEATURE DISPLAY NAMES
# ============================================================

FEATURE_NAMES = {

    "sg": "Specific Gravity",

    "al": "Albumin",

    "hemo": "Hemoglobin",

    "rc": "Red Blood Cell Count",

    "htn": "Hypertension",

    "dm": "Diabetes Mellitus",

    "appet": "Appetite",

    "pc": "Pus Cell"
}


# ============================================================
# eGFR + CKD GFR STAGE (MODULE 5)
# ============================================================

def calculate_egfr(age, gender, creatinine):
    """
    Calculate estimated GFR using the MDRD equation used by this project.

    eGFR = 175 * (Scr ** -1.154) * (Age ** -0.203)
    Female adjustment = 0.742

    Returns eGFR in mL/min/1.73 m², rounded to one decimal place.
    """
    try:
        age = float(age)
        creatinine = float(creatinine)
    except (TypeError, ValueError):
        return None

    if age <= 0 or creatinine <= 0:
        return None

    egfr = 175 * (creatinine ** -1.154) * (age ** -0.203)

    if str(gender).strip().lower() == "female":
        egfr *= 0.742

    return round(float(egfr), 1)


def get_gfr_stage(egfr):
    """Return the KDIGO-style GFR category for a calculated eGFR."""
    if egfr is None:
        return "Not Available"

    egfr = float(egfr)

    if egfr >= 90:
        return "G1"
    elif egfr >= 60:
        return "G2"
    elif egfr >= 45:
        return "G3a"
    elif egfr >= 30:
        return "G3b"
    elif egfr >= 15:
        return "G4"
    else:
        return "G5"


def get_gfr_description(stage):
    descriptions = {
        "G1": "Normal or high",
        "G2": "Mildly decreased",
        "G3a": "Mildly to moderately decreased",
        "G3b": "Moderately to severely decreased",
        "G4": "Severely decreased",
        "G5": "Kidney failure range",
    }
    return descriptions.get(stage, "Not available")


# ============================================================
# DATABASE CONNECTION
# ============================================================

def get_db_connection():

    conn = sqlite3.connect(DATABASE)

    conn.row_factory = sqlite3.Row

    return conn


# ============================================================
# CREATE DATABASE
# ============================================================

def create_database():

    conn = get_db_connection()

    conn.execute("""
        CREATE TABLE IF NOT EXISTS patient_history (

            id INTEGER PRIMARY KEY AUTOINCREMENT,

            patient_name TEXT NOT NULL,

            age REAL,

            sg REAL,

            al REAL,

            hemo REAL,

            rc REAL,

            htn TEXT,

            dm TEXT,

            appet TEXT,

            pc TEXT,

            prediction TEXT,

            risk TEXT,

            confidence REAL,

            ckd_probability REAL,

            gender TEXT,

            serum_creatinine REAL,

            egfr REAL,

            gfr_stage TEXT,

            created_at TEXT

        )
    """)

    conn.commit()

    # Migrate an existing patient_history.db safely.
    columns = conn.execute(
        "PRAGMA table_info(patient_history)"
    ).fetchall()

    column_names = [column["name"] for column in columns]

    if "ckd_probability" not in column_names:
        conn.execute("""
            ALTER TABLE patient_history
            ADD COLUMN ckd_probability REAL
        """)
        conn.commit()
        print("Database updated: ckd_probability column added.")

    # Module 5 migration: eGFR-related fields.
    migrations = {
        "gender": "TEXT",
        "serum_creatinine": "REAL",
        "egfr": "REAL",
        "gfr_stage": "TEXT",
        "bp": "REAL",
    }

    for column, column_type in migrations.items():
        if column not in column_names:
            conn.execute(
                f"ALTER TABLE patient_history ADD COLUMN {column} {column_type}"
            )
            conn.commit()
            print(f"Database updated: {column} column added.")

    conn.close()


create_database()


# ============================================================
# LOAD MODEL
# ============================================================

try:

    with open("Kidney.pkl", "rb") as file:

        model_data = pickle.load(file)


    if isinstance(model_data, dict):

        model = model_data.get("model")

        model_accuracy = model_data.get(
            "accuracy",
            0
        )

    else:

        model = model_data

        model_accuracy = 0


    print()
    print("=" * 60)
    print("MODEL LOADED SUCCESSFULLY")
    print("=" * 60)

    print(
        "MODEL TYPE:",
        type(model).__name__
    )


    if hasattr(model, "classes_"):

        print(
            "MODEL CLASSES:",
            model.classes_
        )

    else:

        print(
            "MODEL CLASSES: Not available"
        )

    print("=" * 60)
    print()


except Exception as e:

    print()
    print("=" * 60)
    print("MODEL LOADING ERROR")
    print("=" * 60)
    print(e)
    print("=" * 60)
    print()

    model = None

    model_accuracy = 0


# ============================================================
# SINGLE SOURCE OF TRUTH — MODEL ACCURACY
# ============================================================
# The deployed model's stored accuracy is the value shown on the
# prediction result and analytics dashboard.
# Independent validation uploads have their own separate accuracy.
try:
    MODEL_ACCURACY_PERCENT = round(
        float(model_accuracy or 0) * 100,
        2
    )
except Exception:
    MODEL_ACCURACY_PERCENT = 0


@app.context_processor
def inject_model_accuracy():
    return {
        "model_accuracy_percent": MODEL_ACCURACY_PERCENT
    }


# ============================================================
# NORMALIZE VALUE
# ============================================================

def normalize_value(value):

    """
    Converts numpy/scikit-learn values into
    simple Python values.
    """

    try:

        if hasattr(
            value,
            "item"
        ):

            value = value.item()

    except Exception:

        pass


    if isinstance(
        value,
        bytes
    ):

        try:

            value = value.decode(
                "utf-8"
            )

        except Exception:

            value = str(value)


    if isinstance(
        value,
        str
    ):

        value = value.strip().lower()


        # Handle strings such as b'ckd'

        if (
            value.startswith("b'")
            and
            value.endswith("'")
        ):

            value = value[2:-1].strip().lower()


        elif (
            value.startswith('b"')
            and
            value.endswith('"')
        ):

            value = value[2:-1].strip().lower()


    return value


# ============================================================
# DECODE CKD LABEL
# ============================================================

def decode_ckd_label(value):

    """
    Converts a model/CSV label into:

        0 = CKD
        1 = No CKD

    Returns None when the value is unknown.

    Supported labels include:

        CKD
        No CKD
        ckd
        notckd
        positive
        negative
        yes
        no
        0
        1
    """

    value = normalize_value(
        value
    )


    # ========================================================
    # NUMERIC
    # ========================================================

    if isinstance(
        value,
        (int, float)
    ):

        try:

            number = float(value)


            if number == 0:

                return 0


            if number == 1:

                return 1


        except Exception:

            pass


    # ========================================================
    # STRING NUMERIC
    # ========================================================

    if isinstance(
        value,
        str
    ):

        if value in [
            "0",
            "0.0"
        ]:

            return 0


        if value in [
            "1",
            "1.0"
        ]:

            return 1


    # ========================================================
    # CKD LABELS
    # ========================================================

    if isinstance(
        value,
        str
    ):

        if value in [

            "ckd",

            "chronic kidney disease",

            "chronic kidney disease detected",

            "disease",

            "positive",

            "yes",

            "ckd detected",

            "ckd_positive",

            "ckd-positive"

        ]:

            return 0


    # ========================================================
    # NO CKD LABELS
    # ========================================================

    if isinstance(
        value,
        str
    ):

        if value in [

            "notckd",

            "not ckd",

            "no ckd",

            "no chronic kidney disease",

            "no chronic kidney disease detected",

            "healthy",

            "negative",

            "no",

            "normal",

            "not disease",

            "non-ckd",

            "non ckd",

            "no_ckd",

            "not_ckd"

        ]:

            return 1


    return None


# ============================================================
# MODEL LABEL DECODER
# ============================================================

def decode_model_prediction(raw_prediction):

    """
    Converts the model's raw prediction into:

        0 = CKD
        1 = No CKD

    The saved model may use different raw class labels.

    Supported examples:

        0 / 1       -> 0 = CKD, 1 = No CKD

        1 / 2       -> 1 = No CKD, 2 = CKD

        'ckd'       -> CKD

        'notckd'    -> No CKD
    """

    # ========================================================
    # NORMALIZE
    # ========================================================

    normalized_prediction = normalize_value(
        raw_prediction
    )


    # ========================================================
    # STRING LABELS
    # ========================================================

    if isinstance(
        normalized_prediction,
        str
    ):

        # ----------------------------------------------------
        # CKD
        # ----------------------------------------------------

        if normalized_prediction in [

            "ckd",
            "chronic kidney disease",
            "chronic kidney disease detected",
            "ckd detected",
            "disease",
            "positive",
            "yes",
            "ckd_positive",
            "ckd-positive"

        ]:

            return 0


        # ----------------------------------------------------
        # NO CKD
        # ----------------------------------------------------

        if normalized_prediction in [

            "notckd",
            "not ckd",
            "no ckd",
            "no chronic kidney disease",
            "no chronic kidney disease detected",
            "healthy",
            "negative",
            "no",
            "normal",
            "not disease",
            "non-ckd",
            "non ckd",
            "no_ckd",
            "not_ckd"

        ]:

            return 1


    # ========================================================
    # MODEL CLASSES
    # ========================================================

    classes = None


    if hasattr(
        model,
        "classes_"
    ):

        try:

            classes = list(
                model.classes_
            )

        except Exception:

            classes = None


    # ========================================================
    # DEBUG INFORMATION
    # ========================================================

    if classes is not None:

        print(
            "MODEL CLASS MAPPING"
        )

        print(
            "Raw prediction:",
            repr(raw_prediction)
        )

        print(
            "Model classes:",
            classes
        )


    # ========================================================
    # CURRENT MODEL:
    #
    # 1 = NO CKD
    # 2 = CKD
    # ========================================================

    if classes is not None:

        try:

            numeric_classes = [

                float(
                    normalize_value(
                        class_value
                    )
                )

                for class_value in classes

            ]


            if set(
                numeric_classes
            ) == {1.0, 2.0}:

                numeric_prediction = float(
                    normalized_prediction
                )


                if numeric_prediction == 2:

                    return 0


                if numeric_prediction == 1:

                    return 1


        except Exception:

            pass


    # ========================================================
    # STANDARD MODEL:
    #
    # 0 = CKD
    # 1 = NO CKD
    # ========================================================

    if classes is not None:

        try:

            numeric_classes = [

                float(
                    normalize_value(
                        class_value
                    )
                )

                for class_value in classes

            ]


            if set(
                numeric_classes
            ) == {0.0, 1.0}:

                numeric_prediction = float(
                    normalized_prediction
                )


                if numeric_prediction == 0:

                    return 0


                if numeric_prediction == 1:

                    return 1


        except Exception:

            pass


    # ========================================================
    # NUMERIC FALLBACK
    # ========================================================

    try:

        numeric_prediction = float(
            normalized_prediction
        )


        # ----------------------------------------------------
        # Current saved model
        #
        # 2 = CKD
        # ----------------------------------------------------

        if numeric_prediction == 2:

            return 0


        # ----------------------------------------------------
        # Existing application convention
        #
        # 0 = CKD
        # 1 = No CKD
        # ----------------------------------------------------

        if numeric_prediction == 0:

            return 0


        if numeric_prediction == 1:

            return 1


    except Exception:

        pass


    # ========================================================
    # UNKNOWN
    # ========================================================

    return None


# ============================================================
# CLEAN VALIDATION DATA
# ============================================================

def prepare_validation_data(df):

    """
    Converts CSV data into exactly the same
    8 model features used during prediction.
    """

    data = df[
        MODEL_FEATURES
    ].copy()


    # ========================================================
    # NUMERIC FEATURES
    # ========================================================

    numerical_features = [

        "sg",
        "al",
        "hemo",
        "rc"

    ]


    for column in numerical_features:

        data[column] = pd.to_numeric(

            data[column],

            errors="coerce"

        )


    # ========================================================
    # TEXT CLEANER
    # ========================================================

    def clean_text(value):

        if pd.isna(value):

            return ""

        return str(
            value
        ).strip().lower()


    # ========================================================
    # HYPERTENSION
    # ========================================================

    data["htn"] = (

        data["htn"]

        .apply(clean_text)

        .map({

            "yes": 1,

            "no": 0,

            "1": 1,

            "0": 0,

            "true": 1,

            "false": 0

        })

    )


    # ========================================================
    # DIABETES
    # ========================================================

    data["dm"] = (

        data["dm"]

        .apply(clean_text)

        .map({

            "yes": 1,

            "no": 0,

            "1": 1,

            "0": 0,

            "true": 1,

            "false": 0

        })

    )


    # ========================================================
    # APPETITE
    # ========================================================

    data["appet"] = (

        data["appet"]

        .apply(clean_text)

        .map({

            "poor": 1,

            "good": 0,

            "1": 1,

            "0": 0

        })

    )


    # ========================================================
    # PUS CELL
    # ========================================================

    data["pc"] = (

        data["pc"]

        .apply(clean_text)

        .map({

            "normal": 1,

            "abnormal": 0,

            "1": 1,

            "0": 0

        })

    )


    # ========================================================
    # FORCE NUMERIC DATA TYPES
    #
    # Prevents XGBoost dtype errors.
    # ========================================================

    for column in MODEL_FEATURES:

        data[column] = pd.to_numeric(

            data[column],

            errors="coerce"

        )


    return data


# ============================================================
# TARGET ENCODING
# ============================================================

def encode_target(value):

    """
    Converts an actual CSV target into:

        0 = CKD
        1 = No CKD

    Also supports numeric 1/2 when the saved model uses:
        1 = No CKD
        2 = CKD
    """

    decoded = decode_ckd_label(value)

    if decoded is not None:
        return decoded

    if hasattr(model, "classes_"):

        try:
            classes = list(model.classes_)

            numeric_classes = [
                float(normalize_value(class_value))
                for class_value in classes
            ]

            if set(numeric_classes) == {1.0, 2.0}:

                numeric_value = float(
                    normalize_value(value)
                )

                if numeric_value == 2:
                    return 0

                if numeric_value == 1:
                    return 1

        except Exception:
            pass

    return None


# ============================================================
# FIND TARGET COLUMN
# ============================================================

def find_target_column(df):

    possible_targets = [

        "classification",

        "class",

        "target",

        "label",

        "ckd",

        "result",

        "outcome",

        "diagnosis",

        "prediction"

    ]


    for column in possible_targets:

        if column in df.columns:

            return column


    return None


# ============================================================
# EXPLAINABLE AI
# ============================================================

def get_prediction_explanation(
    input_data,
    prediction_value
):

    """
    Generates a simple model-factor explanation
    using feature_importances_.

    This is NOT causal medical explanation.

    It identifies which input features have higher
    importance in the trained model.
    """

    explanations = []


    try:

        if not hasattr(
            model,
            "feature_importances_"
        ):

            return explanations


        importances = model.feature_importances_


        if len(importances) != len(
            MODEL_FEATURES
        ):

            return explanations


        feature_data = []


        for index, feature in enumerate(
            MODEL_FEATURES
        ):

            importance = float(
                importances[index]
            )


            value = input_data.iloc[0][
                feature
            ]


            feature_data.append({

                "feature": feature,

                "name": FEATURE_NAMES.get(
                    feature,
                    feature
                ),

                "importance": importance,

                "value": value

            })


        # ====================================================
        # SORT BY IMPORTANCE
        # ====================================================

        feature_data.sort(

            key=lambda x:
            x["importance"],

            reverse=True

        )


        # ====================================================
        # TOTAL IMPORTANCE
        # ====================================================

        total_importance = sum(

            item["importance"]

            for item in feature_data

        )


        # ====================================================
        # TOP 4 FEATURES
        # ====================================================

        for item in feature_data[:4]:

            if total_importance > 0:

                percentage = (

                    item["importance"]

                    /

                    total_importance

                ) * 100

            else:

                percentage = 0


            explanations.append({

                "name": item["name"],

                "value": item["value"],

                "importance": round(
                    percentage,
                    2
                ),

                "message": (

                    f"{item['name']} was one of the "
                    f"higher-importance input factors "
                    f"considered by the trained model."

                )

            })


    except Exception as e:

        print(
            "XAI ERROR:",
            e
        )


    return explanations


# ============================================================
# CLINICAL DECISION SUPPORT / RECOMMENDATION ENGINE
# ============================================================

def get_recommendations(
    prediction_value,
    ckd_probability,
    sg,
    al,
    hemo,
    rc,
    htn_value,
    dm_value,
    appet_value,
    pc_value
):
    """
    Generates rule-based decision-support recommendations from the
    same inputs used by the current ML model.

    This is a support layer, NOT a diagnosis or treatment engine.
    """

    recommendations = []
    warnings = []

    probability = float(ckd_probability or 0)

    htn = str(htn_value or "").strip().lower()
    dm = str(dm_value or "").strip().lower()
    appet = str(appet_value or "").strip().lower()
    pc = str(pc_value or "").strip().lower()

    # ------------------------------------------------------------
    # Overall recommendation
    # ------------------------------------------------------------

    if prediction_value == 0:

        recommendations.append({
            "title": "Medical Follow-up Recommended",
            "message": (
                "The model detected a CKD-associated pattern. "
                "Arrange clinical evaluation and confirm the finding "
                "using appropriate laboratory and medical assessment."
            ),
            "priority": "High"
        })

    elif probability >= 40:

        recommendations.append({
            "title": "Closer Monitoring Suggested",
            "message": (
                "The model-estimated CKD probability is elevated. "
                "Consider repeat assessment and professional clinical "
                "review, especially if symptoms or risk factors are present."
            ),
            "priority": "Moderate"
        })

    else:

        recommendations.append({
            "title": "Continue Routine Kidney Health Monitoring",
            "message": (
                "The current model estimate is relatively low. "
                "Continue routine health monitoring and follow "
                "professional medical advice."
            ),
            "priority": "Low"
        })

    # ------------------------------------------------------------
    # Hypertension
    # ------------------------------------------------------------

    if htn == "yes":

        recommendations.append({
            "title": "Blood Pressure Monitoring",
            "message": (
                "Hypertension was reported. Maintain regular blood "
                "pressure monitoring and discuss blood-pressure "
                "management with a healthcare professional."
            ),
            "priority": "Important"
        })

        warnings.append(
            "Hypertension is an important kidney-health risk factor."
        )

    # ------------------------------------------------------------
    # Diabetes
    # ------------------------------------------------------------

    if dm == "yes":

        recommendations.append({
            "title": "Diabetes Management",
            "message": (
                "Diabetes was reported. Continue appropriate glucose "
                "monitoring and follow the treatment plan provided by "
                "your healthcare professional."
            ),
            "priority": "Important"
        })

        warnings.append(
            "Diabetes can be associated with kidney disease risk."
        )

    # ------------------------------------------------------------
    # Albumin
    # ------------------------------------------------------------

    try:

        if float(al) >= 2:

            recommendations.append({
                "title": "Albumin Result Needs Clinical Review",
                "message": (
                    "The recorded urine albumin value is elevated within "
                    "the model input scale. Discuss the result with a "
                    "healthcare professional and consider appropriate "
                    "urine testing."
                ),
                "priority": "Important"
            })

    except Exception:
        pass

    # ------------------------------------------------------------
    # Hemoglobin
    # ------------------------------------------------------------

    try:

        if float(hemo) < 10:

            recommendations.append({
                "title": "Hemoglobin Result Needs Review",
                "message": (
                    "The recorded hemoglobin value is low. Discuss the "
                    "result with a healthcare professional rather than "
                    "interpreting it in isolation."
                ),
                "priority": "Important"
            })

    except Exception:
        pass

    # ------------------------------------------------------------
    # Appetite
    # ------------------------------------------------------------

    if appet == "poor":

        recommendations.append({
            "title": "Nutrition and Symptom Review",
            "message": (
                "Poor appetite was reported. Discuss persistent appetite "
                "changes or nutritional concerns with a healthcare professional."
            ),
            "priority": "Monitor"
        })

    # ------------------------------------------------------------
    # Pus cell
    # ------------------------------------------------------------

    if pc == "abnormal":

        recommendations.append({
            "title": "Urine Finding Needs Review",
            "message": (
                "An abnormal pus-cell result was reported. Appropriate "
                "clinical interpretation and follow-up urine testing "
                "may be considered by a healthcare professional."
            ),
            "priority": "Monitor"
        })

    # ------------------------------------------------------------
    # Probability-based alert
    # ------------------------------------------------------------

    if probability >= 70:

        warnings.append(
            "The model-estimated CKD probability is high. "
            "Professional clinical review is recommended."
        )

    elif probability >= 40:

        warnings.append(
            "The model-estimated CKD probability is in an elevated range. "
            "Consider closer follow-up."
        )

    # ------------------------------------------------------------
    # Ensure the page always has useful content.
    # ------------------------------------------------------------

    if not recommendations:

        recommendations.append({
            "title": "Maintain Preventive Health Practices",
            "message": (
                "Continue routine health monitoring, healthy lifestyle "
                "practices, and follow-up with a healthcare professional "
                "when appropriate."
            ),
            "priority": "Low"
        })

    return recommendations, warnings


# ============================================================
# CKD PROBABILITY
# ============================================================

def get_ckd_probability(input_data, prediction_value):

    """
    Returns CKD probability specifically.

    Internal representation:
        0 = CKD
        1 = No CKD
    """

    if model is None or not hasattr(model, "predict_proba"):
        return None

    try:

        probabilities = model.predict_proba(input_data)[0]

        if hasattr(model, "classes_"):

            classes = list(model.classes_)

            if len(classes) == len(probabilities):

                for index, class_value in enumerate(classes):

                    decoded_class = decode_model_prediction(
                        class_value
                    )

                    if decoded_class == 0:

                        return round(
                            float(probabilities[index]) * 100,
                            2
                        )

        # Fallback if class metadata is unavailable.
        if prediction_value == 0:

            return round(
                float(max(probabilities)) * 100,
                2
            )

        if len(probabilities) >= 2:

            return round(
                float(min(probabilities)) * 100,
                2
            )

    except Exception as e:

        print("CKD PROBABILITY ERROR:", e)

    return None


# ============================================================
# HOME
# ============================================================

@app.route("/")
@app.route("/home")
def home():

    return render_template(
        "homepage.html"
    )


# ============================================================
# DASHBOARD
# ============================================================

@app.route("/dashboard")
def dashboard():

    return redirect(
        url_for(
            "patient_history"
        )
    )


# ============================================================
# PREDICTION
# ============================================================

@app.route(
    "/predict",
    methods=["GET", "POST"]
)
def predict():

    # ========================================================
    # GET
    # ========================================================

    if request.method == "GET":

        return render_template(
            "predict.html"
        )


    try:

        # ====================================================
        # PATIENT NAME
        # ====================================================

        patient_name = request.form.get(

            "patient_name",

            "Unknown Patient"

        ).strip()


        if not patient_name:

            patient_name = "Unknown Patient"


        # ====================================================
        # AGE
        # ====================================================

        age = float(

            request.form.get(
                "age",
                0
            )

        )

        # Blood Pressure is collected by predict.html and is stored
        # with the assessment so it can be reproduced in the PDF report.
        bp = float(
            request.form.get(
                "bp",
                0
            )
        )

        if bp <= 0:
            raise ValueError(
                "Please enter a valid Blood Pressure value."
            )


        # ====================================================
        # MODULE 5: GENDER + SERUM CREATININE FOR eGFR
        # ====================================================

        gender = request.form.get(
            "gender",
            ""
        ).strip()

        serum_creatinine = float(
            request.form.get(
                "sc",
                0
            )
        )

        if gender.lower() not in ("male", "female"):
            raise ValueError(
                "Please select a valid gender (Male or Female) for eGFR calculation."
            )

        if serum_creatinine <= 0:
            raise ValueError(
                "Please enter a valid Serum Creatinine value for eGFR calculation."
            )

        egfr = calculate_egfr(
            age,
            gender,
            serum_creatinine
        )

        gfr_stage = get_gfr_stage(egfr)
        gfr_description = get_gfr_description(gfr_stage)


        # ====================================================
        # NUMERICAL VALUES
        # ====================================================

        sg = float(
            request.form.get("sg")
        )

        al = float(
            request.form.get("al")
        )

        hemo = float(
            request.form.get("hemo")
        )

        rc = float(
            request.form.get("rc")
        )


        # ====================================================
        # CATEGORICAL VALUES
        # ====================================================

        htn_value = request.form.get(
            "htn",
            ""
        )

        dm_value = request.form.get(
            "dm",
            ""
        )

        appet_value = request.form.get(
            "appet",
            ""
        )

        pc_value = request.form.get(
            "pc",
            ""
        )


        # ====================================================
        # ENCODING
        # ====================================================

        htn = (

            1

            if htn_value.lower() == "yes"

            else 0

        )


        dm = (

            1

            if dm_value.lower() == "yes"

            else 0

        )


        appet = (

            1

            if appet_value.lower() == "poor"

            else 0

        )


        pc = (

            1

            if pc_value.lower() == "normal"

            else 0

        )


        # ====================================================
        # MODEL INPUT
        # ====================================================

        input_data = pd.DataFrame(

            [[

                sg,
                al,
                hemo,
                rc,
                htn,
                dm,
                appet,
                pc

            ]],

            columns=MODEL_FEATURES

        )


        # ====================================================
        # FORCE NUMERIC TYPES
        # ====================================================

        for column in MODEL_FEATURES:

            input_data[column] = pd.to_numeric(

                input_data[column],

                errors="coerce"

            )


        # ====================================================
        # CHECK MODEL
        # ====================================================

        if model is None:

            return render_template(

                "result.html",

                result="Model Error",

                risk="Unknown",

                confidence=0,

                ckd_probability=0,

                gender="",

                serum_creatinine=None,

                egfr=None,

                gfr_stage="Not Available",

                gfr_description="Not available",

                recommendations=[],

                warnings=[],

                accuracy=0,

                patient_name=patient_name,

                age=age,

                explanations=[]

            )


        # ====================================================
        # MODEL PREDICTION
        # ====================================================

        raw_prediction = model.predict(

            input_data

        )[0]


        print()
        print("=" * 60)
        print(
            "RAW MODEL PREDICTION:",
            repr(raw_prediction)
        )


        if hasattr(
            model,
            "classes_"
        ):

            print(
                "MODEL CLASSES:",
                model.classes_
            )

        print("=" * 60)


        # ====================================================
        # DECODE
        # ====================================================

        prediction_value = decode_model_prediction(

            raw_prediction

        )


        if prediction_value is None:

            raise ValueError(

                "The model returned an unsupported "
                f"prediction value: {raw_prediction}. "
                "Supported output is CKD / No CKD, "
                "0 / 1, or the current model's "
                "1 / 2 encoding."

            )


        # ====================================================
        # CONFIDENCE
        # ====================================================

        confidence = 0


        if hasattr(
            model,
            "predict_proba"
        ):

            try:

                probabilities = model.predict_proba(

                    input_data

                )[0]


                confidence = round(

                    float(
                        max(probabilities) * 100
                    ),

                    2

                )

            except Exception as e:

                print(
                    "CONFIDENCE ERROR:",
                    e
                )


        # ====================================================
        # CKD PROBABILITY
        # ====================================================

        ckd_probability = get_ckd_probability(
            input_data,
            prediction_value
        )

        if ckd_probability is None:
            ckd_probability = 0


        # ====================================================
        # CLINICAL DECISION SUPPORT
        # ====================================================

        recommendations, warnings = get_recommendations(
            prediction_value=prediction_value,
            ckd_probability=ckd_probability,
            sg=sg,
            al=al,
            hemo=hemo,
            rc=rc,
            htn_value=htn_value,
            dm_value=dm_value,
            appet_value=appet_value,
            pc_value=pc_value
        )


        # ====================================================
        # RESULT
        #
        # Internal representation:
        #
        # 0 = CKD
        # 1 = NO CKD
        # ====================================================

        if prediction_value == 0:

            result = (
                "Chronic Kidney Disease Detected"
            )

            risk = "High"


        else:

            result = (
                "No Chronic Kidney Disease Detected"
            )

            risk = "Low"


        # ====================================================
        # EXPLAINABLE AI
        # ====================================================

        explanations = get_prediction_explanation(

            input_data,

            prediction_value

        )


        # ====================================================
        # SAVE HISTORY
        # ====================================================

        conn = get_db_connection()


        created_at = datetime.now().strftime(

            "%Y-%m-%d %H:%M:%S"

        )


        cursor = conn.execute(

            """
            INSERT INTO patient_history (

                patient_name,

                age,

                sg,

                al,

                hemo,

                rc,

                htn,

                dm,

                appet,

                pc,

                prediction,

                risk,

                confidence,

                ckd_probability,

                gender,

                serum_creatinine,

                bp,

                egfr,

                gfr_stage,

                created_at

            )

            VALUES (

                ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?,
                ?, ?, ?, ?, ?

            )
            """,

            (

                patient_name,

                age,

                sg,

                al,

                hemo,

                rc,

                htn_value,

                dm_value,

                appet_value,

                pc_value,

                result,

                risk,

                confidence,

                ckd_probability,

                gender,

                serum_creatinine,

                bp,

                egfr,

                gfr_stage,

                created_at

            )

        )


        conn.commit()


        assessment_id = cursor.lastrowid


        conn.close()


        # ====================================================
        # MODEL ACCURACY
        # ====================================================

        # Use the same stored model accuracy everywhere in the app.
        accuracy = MODEL_ACCURACY_PERCENT


        # ====================================================
        # RESULT PAGE
        # ====================================================

        return render_template(

            "result.html",

            result=result,

            risk=risk,

            confidence=confidence,

            ckd_probability=ckd_probability,

            gender=gender,

            serum_creatinine=serum_creatinine,

            egfr=egfr,

            gfr_stage=gfr_stage,

            gfr_description=gfr_description,

            recommendations=recommendations,

            warnings=warnings,

            accuracy=accuracy,

            sg=sg,

            al=al,

            hemo=hemo,

            rc=rc,

            htn=htn_value,

            dm=dm_value,

            appet=appet_value,

            pc=pc_value,

            patient_name=patient_name,

            age=age,

            assessment_id=assessment_id,

            explanations=explanations,

            # Compatibility data used by the result template.
            prediction=result,
            form_data=request.form.to_dict(),

            # Module 5 display helpers.
            stage_info={
                "stage": gfr_stage,
                "label": gfr_stage,
                "desc": gfr_description
            },
            timeline={
                "risk_level": risk,
                "risk_pct": round(float(ckd_probability), 2),
                "timeline": "Based on the current assessment",
                "months": "Follow-up as advised by a healthcare professional",
                "advice": "Review the assessment with a qualified healthcare professional."
            }

        )


    except Exception as e:

        print()
        print(
            "=" * 60
        )

        print(
            "PREDICTION ERROR:"
        )

        print(
            e
        )

        print(
            "=" * 60
        )


        return render_template(

            "predict.html",

            error=str(e)

        )


# ============================================================
# PATIENT HISTORY
# ============================================================

@app.route(
    "/patient-history"
)
@app.route(
    "/history"
)
def patient_history():

    conn = get_db_connection()


    patients = conn.execute(

        """
        SELECT *

        FROM patient_history

        ORDER BY id DESC
        """

    ).fetchall()


    conn.close()


    return render_template(

        "patient_history.html",

        patients=patients,

        assessments=patients

    )


# ============================================================
# SINGLE ASSESSMENT
# ============================================================

@app.route(
    "/assessment/<int:assessment_id>"
)
def assessment(
    assessment_id
):

    conn = get_db_connection()


    patient = conn.execute(

        """
        SELECT *

        FROM patient_history

        WHERE id = ?

        """,

        (
            assessment_id,
        )

    ).fetchone()


    conn.close()


    if patient is None:

        return (
            "Assessment not found",
            404
        )


    return render_template(

        "assessment.html",

        patient=patient

    )


# ============================================================
# PATIENT RISK TREND / PROGRESSION MONITORING
# ============================================================

@app.route(
    "/patient-risk-trend/<path:patient_name>"
)
def patient_risk_trend(patient_name):

    conn = get_db_connection()

    assessments = conn.execute(
        """
        SELECT
            id,
            patient_name,
            age,
            prediction,
            risk,
            confidence,
            ckd_probability,
            created_at
        FROM patient_history
        WHERE patient_name = ?
        ORDER BY created_at ASC, id ASC
        """,
        (patient_name,)
    ).fetchall()

    conn.close()

    if not assessments:
        return (
            "No assessment history found for this patient.",
            404
        )

    trend_data = []

    for assessment in assessments:

        probability = assessment["ckd_probability"]

        # Backward compatibility for old records.
        if probability is None:

            if (
                assessment["prediction"]
                == "Chronic Kidney Disease Detected"
            ):

                probability = float(
                    assessment["confidence"] or 0
                )

            elif (
                assessment["prediction"]
                == "No Chronic Kidney Disease Detected"
            ):

                probability = round(
                    100 - float(
                        assessment["confidence"] or 0
                    ),
                    2
                )

            else:
                probability = 0

        trend_data.append({

            "id": assessment["id"],

            "date": assessment["created_at"],

            "prediction": assessment["prediction"],

            "risk": assessment["risk"],

            "ckd_probability": round(
                float(probability or 0),
                2
            )

        })

    latest = trend_data[-1]

    previous = (
        trend_data[-2]
        if len(trend_data) > 1
        else None
    )

    trend_direction = "Stable"
    trend_change = 0

    if previous:

        trend_change = round(
            latest["ckd_probability"]
            - previous["ckd_probability"],
            2
        )

        if trend_change > 2:
            trend_direction = "Increasing"

        elif trend_change < -2:
            trend_direction = "Decreasing"

    probability = latest["ckd_probability"]

    if probability >= 70:
        trend_risk = "High"

    elif probability >= 40:
        trend_risk = "Moderate"

    else:
        trend_risk = "Low"

    return render_template(
        "patient_risk_trend.html",
        patient_name=patient_name,
        assessments=trend_data,
        latest=latest,
        previous=previous,
        trend_direction=trend_direction,
        trend_change=trend_change,
        trend_risk=trend_risk
    )


# ============================================================
# ANALYTICS
# ============================================================

@app.route(
    "/analytics"
)
def analytics():

    # Keep the analytics dashboard consistent with the deployed model.
    # The template may contain an older hard-coded accuracy from a previous
    # experiment; replace only that legacy value in the rendered HTML.
    rendered = render_template(
        "analytics.html",
        model_accuracy_percent=MODEL_ACCURACY_PERCENT
    )

    rendered = rendered.replace(
        "98.4%",
        f"{MODEL_ACCURACY_PERCENT:.2f}%"
    )

    rendered = rendered.replace(
        "98.4",
        f"{MODEL_ACCURACY_PERCENT:.2f}"
    )

    return rendered


# ============================================================
# ABOUT
# ============================================================

@app.route(
    "/about"
)
def about():

    return render_template(
        "about.html"
    )


# ============================================================
# PREDICTION PAGE ALIAS
# ============================================================

@app.route(
    "/prediction-page"
)
def prediction_page():

    return redirect(

        url_for(
            "predict"
        )

    )


# ============================================================
# MODEL VALIDATION CENTER
# ============================================================

@app.route(
    "/model-validation",
    methods=["GET", "POST"]
)
def model_validation():

    # ========================================================
    # GET
    # ========================================================

    if request.method == "GET":

        return render_template(

            "model_validation.html"

        )


    try:

        # ====================================================
        # CHECK MODEL
        # ====================================================

        if model is None:

            return render_template(

                "model_validation.html",

                error=(
                    "The trained CKD model "
                    "could not be loaded."
                )

            )


        # ====================================================
        # CHECK FILE
        # ====================================================

        if "dataset" not in request.files:

            return render_template(

                "model_validation.html",

                error=(
                    "Please select a CSV dataset."
                )

            )


        file = request.files[
            "dataset"
        ]


        if file.filename == "":

            return render_template(

                "model_validation.html",

                error=(
                    "Please select a CSV dataset."
                )

            )


        # ====================================================
        # CSV CHECK
        # ====================================================

        if not file.filename.lower().endswith(
            ".csv"
        ):

            return render_template(

                "model_validation.html",

                error=(
                    "Only CSV files are supported."
                )

            )


        # ====================================================
        # READ CSV
        # ====================================================

        df = pd.read_csv(
            file
        )


        uploaded_rows = len(
            df
        )


        # ====================================================
        # CLEAN COLUMN NAMES
        # ====================================================

        df.columns = [

            str(column)
            .strip()
            .lower()

            for column in df.columns

        ]


        # ====================================================
        # REQUIRED FEATURES
        # ====================================================

        missing_features = [

            feature

            for feature in MODEL_FEATURES

            if feature not in df.columns

        ]


        if missing_features:

            return render_template(

                "model_validation.html",

                error=(

                    "Dataset is missing required "
                    "columns: "

                    +

                    ", ".join(
                        missing_features
                    )

                )

            )


        # ====================================================
        # FIND TARGET COLUMN
        # ====================================================

        target_column = find_target_column(
            df
        )


        if target_column is None:

            return render_template(

                "model_validation.html",

                error=(

                    "Could not find the actual "
                    "CKD result column. Use one "
                    "of these names: classification, "
                    "class, target, label, ckd, "
                    "result, outcome or diagnosis."

                )

            )


        # ====================================================
        # PREPARE FEATURES
        # ====================================================

        validation_data = prepare_validation_data(
            df
        )


        # ====================================================
        # INVALID ROW DETAILS
        # ====================================================

        invalid_rows = []

        valid_indices = []


        # ====================================================
        # CHECK EACH ROW
        # ====================================================

        for index in range(
            len(df)
        ):

            reasons = []


            # ------------------------------------------------
            # CHECK MODEL FEATURES
            # ------------------------------------------------

            for feature in MODEL_FEATURES:

                value = validation_data.iloc[index][
                    feature
                ]


                if pd.isna(value):

                    reasons.append(

                        f"Invalid or missing value "
                        f"in '{feature}'"

                    )


            # ------------------------------------------------
            # CHECK TARGET
            # ------------------------------------------------

            actual_value = df.iloc[index][
                target_column
            ]


            actual_encoded = encode_target(
                actual_value
            )


            if actual_encoded is None:

                reasons.append(

                    "Unsupported target value: "
                    f"{actual_value}"

                )


            # ------------------------------------------------
            # INVALID
            # ------------------------------------------------

            if reasons:

                invalid_rows.append({

                    "row": index + 1,

                    "reasons": reasons

                })

                continue


            # ------------------------------------------------
            # VALID
            # ------------------------------------------------

            valid_indices.append(
                index
            )


        # ====================================================
        # RUN MODEL
        # ====================================================

        valid_results = []

        prediction_errors = []


        for index in valid_indices:

            try:

                single_row = validation_data.iloc[
                    [index]
                ].copy()


                # --------------------------------------------
                # FORCE NUMERIC TYPES
                # --------------------------------------------

                for feature in MODEL_FEATURES:

                    single_row[feature] = pd.to_numeric(

                        single_row[feature],

                        errors="coerce"

                    )


                # --------------------------------------------
                # MODEL PREDICTION
                # --------------------------------------------

                raw_prediction = model.predict(

                    single_row

                )[0]


                print(
                    "VALIDATION ROW",
                    index + 1,
                    "RAW PREDICTION:",
                    repr(raw_prediction)
                )


                if hasattr(
                    model,
                    "classes_"
                ):

                    print(
                        "MODEL CLASSES:",
                        model.classes_
                    )


                # --------------------------------------------
                # DECODE PREDICTION
                # --------------------------------------------

                decoded_prediction = decode_model_prediction(

                    raw_prediction

                )


                if decoded_prediction is None:

                    prediction_errors.append({

                        "row": index + 1,

                        "reason": (

                            "Model returned an unsupported "
                            "prediction value: "

                            +

                            str(
                                raw_prediction
                            )

                        )

                    })

                    continue


                # --------------------------------------------
                # ACTUAL VALUE
                # --------------------------------------------

                actual_encoded = encode_target(

                    df.iloc[index][
                        target_column
                    ]

                )


                valid_results.append({

                    "index": index,

                    "actual": actual_encoded,

                    "predicted": decoded_prediction

                })


            except Exception as row_error:

                prediction_errors.append({

                    "row": index + 1,

                    "reason": (

                        "Model prediction failed: "

                        +

                        str(
                            row_error
                        )

                    )

                })


        # ====================================================
        # ADD MODEL ERRORS TO INVALID ROWS
        # ====================================================

        for error_item in prediction_errors:

            invalid_rows.append({

                "row": error_item["row"],

                "reasons": [

                    error_item["reason"]

                ]

            })


        # ====================================================
        # TOTAL VALID SAMPLES
        # ====================================================

        total_samples = len(
            valid_results
        )


        # ====================================================
        # TOTAL INVALID
        # ====================================================

        invalid_count = len(
            invalid_rows
        )


        # ====================================================
        # NO VALID ROWS
        # ====================================================

        if total_samples == 0:

            return render_template(

                "model_validation.html",

                validation_complete=True,

                validation_status="Failed",

                filename=file.filename,

                target_column=target_column,

                uploaded_rows=uploaded_rows,

                total_samples=0,

                valid_rows=0,

                invalid_rows_count=invalid_count,

                invalid_row_details=invalid_rows,

                skipped_rows=invalid_count,

                correct_predictions=0,

                incorrect_predictions=0,

                accuracy=0,

                precision=0,

                recall=0,

                specificity=0,

                f1=0,

                true_positive=0,

                true_negative=0,

                false_positive=0,

                false_negative=0,

                comparison=[],

                error=(

                    "No valid rows could be evaluated. "
                    "Please check the dataset values "
                    "and model output."

                )

            )


        # ====================================================
        # ACTUAL VALUES
        # ====================================================

        y_actual = pd.Series([

            item["actual"]

            for item in valid_results

        ])


        # ====================================================
        # PREDICTED VALUES
        # ====================================================

        y_pred = pd.Series([

            item["predicted"]

            for item in valid_results

        ])


        # ====================================================
        # ACCURACY
        # ====================================================

        accuracy = accuracy_score(

            y_actual,

            y_pred

        )


        # ====================================================
        # PRECISION
        #
        # CKD = POSITIVE CLASS = 0
        # ====================================================

        precision = precision_score(

            y_actual,

            y_pred,

            pos_label=0,

            zero_division=0

        )


        # ====================================================
        # RECALL / SENSITIVITY
        # ====================================================

        recall = recall_score(

            y_actual,

            y_pred,

            pos_label=0,

            zero_division=0

        )


        # ====================================================
        # F1 SCORE
        # ====================================================

        f1 = f1_score(

            y_actual,

            y_pred,

            pos_label=0,

            zero_division=0

        )


        # ====================================================
        # CONFUSION MATRIX
        #
        #              PREDICTED
        #
        #              CKD    NO CKD
        #
        # ACTUAL CKD   TP      FN
        #
        # ACTUAL NO    FP      TN
        #
        # labels=[0,1]
        # ====================================================

        cm = confusion_matrix(

            y_actual,

            y_pred,

            labels=[0, 1]

        )


        true_positive = int(
            cm[0][0]
        )


        false_negative = int(
            cm[0][1]
        )


        false_positive = int(
            cm[1][0]
        )


        true_negative = int(
            cm[1][1]
        )


        # ====================================================
        # SPECIFICITY
        # ====================================================

        specificity_denominator = (

            true_negative

            +

            false_positive

        )


        if specificity_denominator > 0:

            specificity = (

                true_negative

                /

                specificity_denominator

            )

        else:

            specificity = 0


        # ====================================================
        # CORRECT PREDICTIONS
        # ====================================================

        correct_predictions = int(

            (
                y_actual.reset_index(drop=True)

                ==

                y_pred.reset_index(drop=True)

            ).sum()

        )


        # ====================================================
        # INCORRECT PREDICTIONS
        # ====================================================

        incorrect_predictions = (

            total_samples

            -

            correct_predictions

        )


        # ====================================================
        # SAMPLE COMPARISON
        #
        # Show first 10 evaluated samples.
        # ====================================================

        comparison = []


        for sample_number, item in enumerate(
            valid_results[:10],
            start=1
        ):

            # ----------------------------------------------
            # ACTUAL LABEL
            # ----------------------------------------------

            if item["actual"] == 0:

                actual_label = "CKD"

            else:

                actual_label = "No CKD"


            # ----------------------------------------------
            # PREDICTED LABEL
            # ----------------------------------------------

            if item["predicted"] == 0:

                predicted_label = "CKD"

            else:

                predicted_label = "No CKD"


            # ----------------------------------------------
            # STATUS
            # ----------------------------------------------

            if (

                item["actual"]

                ==

                item["predicted"]

            ):

                status = "Correct"

            else:

                status = "Incorrect"


            comparison.append({

                "row": item["index"] + 1,

                "sample": sample_number,

                "actual": actual_label,

                "predicted": predicted_label,

                "status": status

            })


        # ====================================================
        # VALIDATION STATUS
        # ====================================================

        if invalid_count == 0:

            validation_status = "Validated"

        else:

            validation_status = "Needs Review"


        # ====================================================
        # FINAL RESULT
        # ====================================================

        return render_template(

            "model_validation.html",

            validation_complete=True,

            validation_status=validation_status,

            filename=file.filename,

            target_column=target_column,

            uploaded_rows=uploaded_rows,

            total_samples=total_samples,

            valid_rows=total_samples,

            invalid_rows_count=invalid_count,

            invalid_row_details=invalid_rows,

            skipped_rows=invalid_count,

            correct_predictions=correct_predictions,

            incorrect_predictions=incorrect_predictions,

            accuracy=round(

                accuracy * 100,

                2

            ),

            precision=round(

                precision * 100,

                2

            ),

            recall=round(

                recall * 100,

                2

            ),

            specificity=round(

                specificity * 100,

                2

            ),

            f1=round(

                f1 * 100,

                2

            ),

            true_positive=true_positive,

            true_negative=true_negative,

            false_positive=false_positive,

            false_negative=false_negative,

            comparison=comparison

        )


    except Exception as e:

        print()
        print(
            "=" * 60
        )

        print(
            "MODEL VALIDATION ERROR:"
        )

        print(
            e
        )

        print(
            "=" * 60
        )


        return render_template(

            "model_validation.html",

            error=(

                "Validation failed: "

                +

                str(e)

            )

        )



# ============================================================
# MODULE 7 — PDF REPORT + WHATSAPP SHARING
# ============================================================

def _report_text(value, default="N/A"):
    """Convert database values safely to displayable report text."""
    if value is None or str(value).strip() == "":
        return default
    return str(value)


def _report_para(text, style):
    """Create a ReportLab paragraph with safe HTML escaping."""
    return Paragraph(html.escape(_report_text(text)).replace("\n", "<br/>"), style)


def build_assessment_pdf(patient, lang='en'):
    lang = report_lang(lang)
    labels = REPORT_LABELS[lang]
    """Build a professional PDF report from a saved patient_history row."""
    patient = dict(patient)

    # Recreate the recommendation/XAI information from the saved assessment.
    prediction_text = _report_text(patient.get("prediction"))
    risk = _report_text(patient.get("risk"))
    confidence = patient.get("confidence")
    ckd_probability = patient.get("ckd_probability")
    age = patient.get("age")
    gender = _report_text(patient.get("gender"))
    serum_creatinine = patient.get("serum_creatinine")
    egfr = patient.get("egfr")
    gfr_stage = _report_text(patient.get("gfr_stage"), "Not Available")

    # Rebuild recommendations using exactly the same decision-support engine.
    try:
        recommendations, warnings = get_recommendations(
            prediction_value=0 if prediction_text == "Chronic Kidney Disease Detected" else 1,
            ckd_probability=float(ckd_probability or 0),
            sg=float(patient.get("sg") or 0),
            al=float(patient.get("al") or 0),
            hemo=float(patient.get("hemo") or 0),
            rc=float(patient.get("rc") or 0),
            htn_value=_report_text(patient.get("htn"), ""),
            dm_value=_report_text(patient.get("dm"), ""),
            appet_value=_report_text(patient.get("appet"), ""),
            pc_value=_report_text(patient.get("pc"), "")
        )
    except Exception:
        recommendations, warnings = [], []

    # Rebuild XAI factor explanation when the model is available.
    explanations = []
    try:
        input_data = pd.DataFrame([[
            float(patient.get("sg") or 0),
            float(patient.get("al") or 0),
            float(patient.get("hemo") or 0),
            float(patient.get("rc") or 0),
            1 if str(patient.get("htn", "")).lower() == "yes" else 0,
            1 if str(patient.get("dm", "")).lower() == "yes" else 0,
            1 if str(patient.get("appet", "")).lower() == "poor" else 0,
            1 if str(patient.get("pc", "")).lower() == "normal" else 0,
        ]], columns=MODEL_FEATURES)
        prediction_value = 0 if prediction_text == "Chronic Kidney Disease Detected" else 1
        explanations = get_prediction_explanation(input_data, prediction_value)
    except Exception:
        explanations = []

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()
    report_font = "NotoTamil" if lang == "ta" and TAMIL_FONT_AVAILABLE else "Helvetica"
    title = ParagraphStyle(
        "CKDReportTitle", parent=styles["Title"], alignment=TA_CENTER,
        fontName=report_font, fontSize=21, leading=25, spaceAfter=5
    )
    subtitle = ParagraphStyle(
        "CKDReportSubtitle", parent=styles["Normal"], alignment=TA_CENTER,
        fontName=report_font, fontSize=9.5, leading=13, spaceAfter=16
    )
    section = ParagraphStyle(
        "CKDReportSection", parent=styles["Heading2"],
        fontName=report_font, fontSize=13, leading=17, spaceBefore=12, spaceAfter=7
    )
    body = ParagraphStyle(
        "CKDReportBody", parent=styles["BodyText"],
        fontName=report_font, fontSize=9.2, leading=13
    )
    small = ParagraphStyle(
        "CKDReportSmall", parent=styles["BodyText"],
        fontName=report_font, fontSize=8, leading=11
    )

    story = [
        Paragraph("CKDPredict", title),
        Paragraph(labels["subtitle"], subtitle),
    ]

    # 1. Assessment summary
    story.append(Paragraph(labels["summary"], section))
    summary = [
         [labels["assessment_id"], _report_text(patient.get("id"))],
         [labels["date"], _report_text(patient.get("created_at"))],
         [labels["patient"], _report_text(patient.get("patient_name"))],
         [labels["age"], _report_text(age)],
         [labels["gender"], gender],
         [labels["prediction"], rtext(prediction_text, lang)],
         [labels["risk"], rtext(risk, lang)],
         [labels["confidence"], f"{float(confidence):.2f}%" if confidence is not None else "N/A"],
         [labels["probability"], f"{float(ckd_probability):.2f}%" if ckd_probability is not None else "N/A"],
    ]
    table = Table(summary, colWidths=[1.85*inch, 4.55*inch])
    table.setStyle(TableStyle([
        ("GRID", (0,0), (-1,-1), 0.4, colors.grey),
        ("BACKGROUND", (0,0), (0,-1), colors.whitesmoke),
        ("FONTNAME", (0,0), (0,-1), report_font),
        ("VALIGN", (0,0), (-1,-1), "TOP"),
        ("PADDING", (0,0), (-1,-1), 6),
        ("FONTSIZE", (0,0), (-1,-1), 8.5),
    ]))
    story += [table, Spacer(1, 8)]

    # 2. Kidney function
    story.append(Paragraph(labels["kidney"], section))
    kidney_rows = [
         [labels["creatinine"], _report_text(serum_creatinine) + " mg/dL"],
         [labels["egfr"], _report_text(egfr) + " mL/min/1.73 m²"],
         [labels["category"], gfr_stage],
         [labels["description"], get_gfr_description(gfr_stage)],
    ]
    kt = Table(kidney_rows, colWidths=[1.85*inch, 4.55*inch])
    kt.setStyle(TableStyle([
        ("GRID", (0,0), (-1,-1), 0.4, colors.grey),
        ("BACKGROUND", (0,0), (0,-1), colors.whitesmoke),
        ("FONTNAME", (0,0), (0,-1), report_font),
        ("PADDING", (0,0), (-1,-1), 6),
        ("FONTSIZE", (0,0), (-1,-1), 8.5),
    ]))
    story += [kt, Spacer(1, 4)]
    story.append(_report_para(
        labels["egfr_note"],
        small
    ))

    # 3. Key clinical parameters
    story.append(Paragraph(labels["clinical"], section))
    clinical = [
        ["Parameter", "Recorded Value"],
        ["Specific Gravity", _report_text(patient.get("sg"))],
        ["Albumin", _report_text(patient.get("al"))],
        ["Hemoglobin", _report_text(patient.get("hemo"))],
        ["RBC Count", _report_text(patient.get("rc"))],
        ["Blood Pressure", _report_text(patient.get("bp"), "Not stored")],
    ]
    ct = Table(clinical, colWidths=[2.6*inch, 3.8*inch], repeatRows=1)
    ct.setStyle(TableStyle([
        ("GRID", (0,0), (-1,-1), 0.4, colors.grey),
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#1d4ed8")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), report_font),
        ("PADDING", (0,0), (-1,-1), 6),
        ("FONTSIZE", (0,0), (-1,-1), 8.5),
    ]))
    story.append(ct)

    # 4. Medical history
    story.append(Paragraph(labels["history"], section))
    history = [
        ["Factor", "Value"],
        ["Hypertension", _report_text(patient.get("htn"))],
        ["Diabetes Mellitus", _report_text(patient.get("dm"))],
        ["Appetite", _report_text(patient.get("appet"))],
        ["Pus Cell", _report_text(patient.get("pc"))],
    ]
    ht = Table(history, colWidths=[2.6*inch, 3.8*inch], repeatRows=1)
    ht.setStyle(TableStyle([
        ("GRID", (0,0), (-1,-1), 0.4, colors.grey),
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#1d4ed8")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), report_font),
        ("PADDING", (0,0), (-1,-1), 6),
        ("FONTSIZE", (0,0), (-1,-1), 8.5),
    ]))
    story.append(ht)

    # 5. XAI
    # The explanation engine returns:
    #   name, value, importance, message
    # Older PDF code expected different keys (feature, impact, reason),
    # which caused blank XAI details in the generated PDF.
    story.append(Paragraph(labels["xai"], section))
    if explanations:
        for item in explanations[:6]:
            if isinstance(item, dict):
                feature = item.get("name", item.get("feature", "Feature"))
                value = item.get("value", "N/A")
                importance = item.get("importance", item.get("impact", "N/A"))
                reason = item.get(
                    "message",
                    item.get("reason", "Model factor considered in the prediction.")
                )
            else:
                feature = "Feature"
                value = "N/A"
                importance = "N/A"
                reason = "Model factor considered in the prediction."

            xai_text = (
                f"{feature}: value={value}; "
                f"model importance={importance}%. {reason}"
            )

            story.append(_report_para(xai_text, body))
            story.append(Spacer(1, 3))
    else:
        story.append(
            _report_para(
                "Feature explanation was not available for this saved assessment.",
                body
            )
        )

    # 6. Warnings + recommendations
    story.append(Paragraph(labels["support"], section))
    if warnings:
        story.append(Paragraph(labels["warnings"], styles["Heading3"]))
        for warning in warnings:
            # The recommendation engine currently returns warning messages
            # as strings. Older versions may return dictionaries, so support
            # both formats to keep PDF generation backward-compatible.
            if isinstance(warning, dict):
                warning_text = (
                    f"{warning.get('param', 'Parameter')}: "
                    f"{warning.get('value', 'N/A')} — "
                    f"{warning.get('message', '')}"
                )
            else:
                warning_text = str(warning)

            story.append(_report_para("• " + warning_text, body))
            story.append(Spacer(1, 3))
    if recommendations:
        story.append(Paragraph(labels["recommendations"], styles["Heading3"]))
        for recommendation in recommendations:
            if isinstance(recommendation, dict):
                title = recommendation.get("title", "Recommendation")
                message = recommendation.get("message", "")
                priority = recommendation.get("priority", "")
                recommendation_text = f"{title}"
                if priority:
                    recommendation_text += f" [{priority}]"
                if message:
                    recommendation_text += f": {message}"
            else:
                recommendation_text = str(recommendation)

            story.append(_report_para("• " + recommendation_text, body))
            story.append(Spacer(1, 3))
    if not warnings and not recommendations:
        story.append(_report_para("No additional decision-support items were generated.", body))

    story.append(Spacer(1, 12))
    story.append(Paragraph(labels["notice"], section))
    story.append(_report_para(
        labels["not_diagnosis"],
        small
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer


@app.route("/download-report/<int:assessment_id>")
def download_report(assessment_id):
    """Generate and download a PDF report for a saved assessment."""
    conn = get_db_connection()
    patient = conn.execute(
        "SELECT * FROM patient_history WHERE id = ?",
        (assessment_id,)
    ).fetchone()
    conn.close()

    if patient is None:
        return "Assessment not found.", 404

    lang = report_lang(request.args.get("lang", "en"))
    pdf_buffer = build_assessment_pdf(patient, lang=lang)
    safe_name = "".join(
        ch for ch in str(patient["patient_name"] or "Patient")
        if ch.isalnum() or ch in "-_"
    ) or "Patient"
    suffix = "_Tamil" if lang == "ta" else "_English"
    filename = f"CKDPredict_Report_{safe_name}_{assessment_id}{suffix}.pdf"

    return send_file(
        pdf_buffer,
        as_attachment=True,
        download_name=filename,
        mimetype="application/pdf"
    )


@app.route("/whatsapp-report/<int:assessment_id>")
def whatsapp_report(assessment_id):
    """Open WhatsApp with a concise assessment summary ready to share."""
    conn = get_db_connection()
    patient = conn.execute(
        "SELECT * FROM patient_history WHERE id = ?",
        (assessment_id,)
    ).fetchone()
    conn.close()

    if patient is None:
        return "Assessment not found.", 404

    confidence = patient["confidence"]
    probability = patient["ckd_probability"]
    egfr = patient["egfr"]
    stage = patient["gfr_stage"] or "Not Available"

    lang = report_lang(request.args.get("lang", "en"))
    if lang == "ta":
        message = (
            "CKDPredict — மதிப்பீட்டு அறிக்கை\n\n"
            f"நோயாளி: {patient['patient_name']}\n"
            f"மதிப்பீட்டு எண்: {patient['id']}\n"
            f"கணிப்பு முடிவு: {rtext(patient['prediction'], 'ta')}\n"
            f"ஆபத்து நிலை: {rtext(patient['risk'], 'ta')}\n"
            f"மாதிரி நம்பிக்கை: {confidence if confidence is not None else 'N/A'}%\n"
            f"CKD நிகழ்தகவு: {probability if probability is not None else 'N/A'}%\n"
            f"eGFR: {egfr if egfr is not None else 'N/A'} mL/min/1.73 m²\n"
            f"GFR வகை: {stage}\n\n"
            "இது முடிவு ஆதரவு தகவல் மட்டுமே; மருத்துவ நோயறிதல் அல்ல."
        )
    else:
        message = (
            "CKDPredict — Assessment Report\n\n"
            f"Patient: {patient['patient_name']}\n"
            f"Assessment ID: {patient['id']}\n"
            f"Prediction: {patient['prediction']}\n"
            f"Risk Level: {patient['risk']}\n"
            f"Model Confidence: {confidence if confidence is not None else 'N/A'}%\n"
            f"CKD Probability: {probability if probability is not None else 'N/A'}%\n"
            f"eGFR: {egfr if egfr is not None else 'N/A'} mL/min/1.73 m²\n"
            f"GFR Category: {stage}\n\n"
            "This is a decision-support result and not a medical diagnosis."
        )

    return redirect("https://wa.me/?text=" + quote(message))

# ============================================================
# APPLICATION START
# ============================================================

if __name__ == "__main__":

    app.run(

        debug=True

    )
